config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: "pages#about"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: :true,
                    length: {minimum: 5}
  validates :body, presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:body), user_id: @current_user.id)

    redirect_to post_path(@post)
  end

  before_filter :authorize

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  before_filter :authorize, :except => [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
      @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.author.username %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <%= if comment.user == @current_user.id %>
    <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete,
                    class: "button",
                    data: { confirm: "Are you sure?" } %>
    </p>
  <%= end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="#">Twitter</a></li>
      <li><a href="#">GitHub</a></li>
      <li><a href="#">LinkedIn</a></li>
      <li><a href="#">Email</a></li>
    </ul>
    <% if not current_user %>
      <p class="sign_in"><%= link_to "Login", login_path %></p>
    <% end %>
  </div>
  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% elsif current_page?(about_path) %>
        <p>About</p>
      <% else %>
        <%= link_to "Back to All Posts", root_path %>
      <% end %>

      <% if current_user %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button"><%= link_to "Log Out", logout_path %></button>
        </div>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>

  </div>


</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.gif" %>
  </div>

  <div id="content">
    <h1>Hi! I'm THE ADMIN.</h1>
    <p>Four dollar toast XOXO tote bag, Truffaut letterpress vinyl PBR&B. Helvetica jean shorts crucifix High Life, distillery skateboard cred Etsy Brooklyn retro. XOXO leggings tilde, banjo art party flannel Schlitz fixie Etsy. Echo Park iPhone PBR&B, tote bag cliche gentrify gastropub Carles food truck ennui try-hard mlkshk Etsy. Tattooed craft beer Etsy cornhole. Wolf church-key VHS quinoa readymade. Quinoa ethical scenester, mlkshk viral brunch street art chia occupy cold-pressed meggings blog lo-fi irony.</p>
    <p></p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    <% if current_user == @post.user %>
      <%= link_to 'Edit', edit_post_path(@post) %>
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>